### PR TITLE
Adding indexing support (updated)

### PR DESCRIPTION
**Pull request by yzubkov**
Please review this PR to add support for managing indexes. I have figured out how to add indexing options. This change will allow adding, removing and searching  for indexes in a collection. Let me know if I can help with anything or if I need to change something. Thanks,

Yaroslav.

### CODE REVIEW

**Comment by christopherjwang** [comment]
Awesome, thanks for this. I'll be able to take a look within the week. I'd be happy to work with you on this if it needs improvements.

**Comment by christopherjwang** [comment]
There are also some style tips we can go over after we get functionality down.

You should always have spaces before and after the equal sign, indenting should always be consistent, and some other things. Don't worry, I do it as well. We'll pretty it up in no time at all.

**Comment by yzubkov** [comment]
Thank you very much for your response. I appreciate your feedback and agree with you that we should make this as good as we can before merging this into the master. I do continue to learn C and am very thankful for your willingness to explain the reason why we do things a certain way. 

Please have another look at my suggested changes. Thanks to you I had to catch up on my knowledge of Lua C API and it is totally my oversight that I did not think of reading lua table directly. In the new version I am using `lua_getfield()` function to push the specific key value onto the stack. The alternative is to create a loop over the keys of the lua options table, but that might be an overkill since we are dealing with a discrete list of options that are passed. Please let me know if I should attempt to re-write this as a loop?

I also think that following PyMongo example is a great idea because it is the most official reference implementation. Before continuing making changes or trying to implement new functionality (Geoindexing, etc..) I would like to get your feedback and see if there is anything I can help with.

**Comment by christopherjwang** [comment]
Cool. I'm going to open up a new branch in this mongo-labs repo and we can work on it.

I'm going to start adding an `IndexModel` implementation, and add test cases. Your work so far looks pretty good. I'll make some small changes to what you've done, since it's not worth going back and forth for those.

**Comment by christopherjwang** [comment]
@yzubkov let's continue this conversation in #65.

**Comment by christopherjwang** [comment]
@yzubkov I apologize, let's actually continue this conversation in #66.

**Pull request merged**
